### ISSUE TITLE
WriteText won't output Figure

### ISSUE THREAD

**Issue by isabelcpv** [wanglongqi/WriteTeX#12]
Hi!
I have Inkscape 0.92.3, running over Win10 and I'm trying to write Latex equations with WriteTeX 1.6.2.
I installed the extension, following the instructions on the [guide](https://writetex.tk/).

My problem:
I write an equation (with the proper preamble) in the WriteTeX form and select to write output to Figure. However no Figure is generated, just a very fast pop up (error?)message.

![image](https://user-images.githubusercontent.com/6452547/46196427-5864f980-c307-11e8-8e00-15d820918104.png)

**Comment by wanglongqi** [comment]
Yes, there should be a error message box popped out and stay there if anything goes wrong. If not, then it is likely the equation has already generated. You can close the extension window and search for it.

**Comment by isabelcpv** [comment]
> 
> 
> Yes, there should be a error message box popped out and stay there if anything goes wrong. If not, then it is likely the equation has already generated. You can close the extension window and search for it.

The pop up disappears instantly, and the equation is not generated. I have looked in all the work frame and it is not there.

**Comment by isabelcpv** [comment]
> 
> 
> Can you help check whether Inkscape change its Python interpreter to Python 3? Refer to this issue #13 . If so, can you also test the version in the repository? Or may rollback to old Inkscape version. I remember that Inkscape 0.92 is still Python 2.

I'm using Inkscape 0.92.3, the Python version is 2.7.
I have no problem using Inkscape neither other extensions. Problem seems to be with WriteText

**Comment by wanglongqi** [comment]
I do not have enough information to diagnose the problem and I can not reproduce your bug on my machine.
