### ISSUE TITLE
Won't render equations

### ISSUE THREAD

**Issue by josephcslater** [wanglongqi/WriteTeX#13]
I'm getting the following error in a "simple" installation on Ubuntu. 

The equation is just a test, $\alpha$. ANy idea what's failing and how to fix it?
![untitled 2](https://user-images.githubusercontent.com/12815335/46261398-07006a00-c4c1-11e8-8af8-2ab99cf90d14.png)

**Comment by wanglongqi** [comment]
Okay, seems you are using Python 3 as Inkscape Python interpreter.

**Comment by josephcslater** [comment]
I'm getting an error: empty LaTeX input. Nothing is changed. 
now

**Comment by wanglongqi** [comment]
Can you give me a screenshot on the error?

**Comment by josephcslater** [comment]
<img width="987" alt="image" src="https://user-images.githubusercontent.com/12815335/46909414-14294a00-cf00-11e8-91df-58f1a845e1a1.png">

Sorry for the delay. Please find it above.

**Comment by wanglongqi** [comment]
Can you input the tex source in the LateX Source box and test?
![image](https://user-images.githubusercontent.com/6874783/46911345-37e5a200-cf8b-11e8-921f-35047f52713e.png)
