### ISSUE TITLE
error

### ISSUE THREAD

**Issue by haohaoxiao** [wanglongqi/WriteTeX#14]
'''''
Latex error: check your latex file and preamble.
Traceback (most recent call last):
  File "writetex.py", line 347, in <module>
    e.affect()
  File "inkex.py", line 283, in affect
    self.effect()
  File "writetex.py", line 158, in effect
    print(open(log_file).read(),file=sys.stderr)
IOError: [Errno 2] No such file or directory: 'c:\\users\\haohao~1\\appdata\\local\\temp\\writetex-ugpec8\\writetex.log'
'''''''''

I have tried a  lot of times on win10.

**Comment by wanglongqi** [comment]
Please share a screenshot on the input.

**Comment by haohaoxiao** [comment]
![default](https://user-images.githubusercontent.com/16067589/47828456-32c38800-ddbe-11e8-8e36-dfc0894cae3c.png)
![default](https://user-images.githubusercontent.com/16067589/47828461-3bb45980-ddbe-11e8-9ce5-22a1aeb4ecdc.png)

**Comment by wanglongqi** [comment]
If you remove the preamble, what will happen?

You can also comment out [these lines](https://github.com/wanglongqi/WriteTeX/blob/ac1105f295cb483a750a1ab09903578b713ba63c/writetex.py#L170-L181) and check the temporary folder to see what happened.

**Comment by haohaoxiao** [comment]
The problem is the variable tmp_dir passed to command xelatex.
The user name of my computer exceeds 8 characters. So the 'username' in the tmp_dir variable uses the short format "haohao~1" insteadly.

However, for some reason, the variable `tmp_dir` passed to xelatex contains some spaces between ~ and 1. That's why xelatex throwed an error when reading the 'writetex.tex' file.

I changed the system's temp varible to another directory for the time being and writetex works again.

**Comment by wanglongqi** [comment]
Thanks for updating. Do not know how `xelatex` handles the short format path. If you find a solution for this issue, please make a PR. Thanks!

**Comment by haohaoxiao** [comment]
It's not the problem of xelatex. I have tried the command "xelatex c:\user\haohao~1\.......writetex.tex", and xelatex works well.

The problem is the variable 'tmp_dir' passed to xelatex seems like:
`c:\user\haohao~
      1\......writetex.tex'

So xelatex just got the contents before 1.

**Comment by wanglongqi** [comment]
I cannot find similar issue on internet. Python's [mkstemp](https://stackoverflow.com/questions/3890233/why-is-tempfile-using-dos-8-3-directory-names-on-my-xp-box) seems working correctly. If you have time, please try to find out a valid command by using [custom latex command function](https://writetex.tk/latexcmd.html).
