### ISSUE TITLE
update the "Latex source" field with the current selected equation in the drawing.

### ISSUE THREAD

**Issue by RaulDurand** [wanglongqi/WriteTeX#15]
It seems that the "LateX source" field only keeps the last typed source.
It would be nice if this field is updated according to the equation selected in the drawing.
This will easy the edition of existing equations.

**Comment by wanglongqi** [comment]
This is not possible to do in native inkscape extension mode, and the main reason why we have a view original tex tab in the extension. You may want to try textext which use pyGTK and thus possible to dynamically obtain information from objects.

**Comment by wanglongqi** [comment]
You may also want to check this version of [WriteTeX](https://github.com/wanglongqi/WriteTeX2).
