### ISSUE TITLE
Add the option to use the "pdftocario" as the pdf to svg converter

### ISSUE THREAD

**Issue by qcts33** [wanglongqi/WriteTeX#16]
The install of both `pdf2svg` and `pstoedit` are kind of painful in windows.
However, I found that `pdftocairo` can also be used to produce the SVG file with the `-svg` option. Since `pdftocairo` is shipped with `texlive`, I think it is a good option for the windows users. 
(I'm not sure about the `miktex`)
A quick referece: https://manpages.debian.org/jessie/poppler-utils/pdftocairo.1.en.html

**Comment by wanglongqi** [comment]
You are welcomed to implement another converter for this plugin.

**Comment by wanglongqi** [comment]
`pdftocario` uses symbol defs extensively. This may be a potential problem when inserting more than one equations.
 
The exported result seems have following structure:
1. symbol defs:

```
<defs>
<symbol overflow="visible" id="glyph0-0">
<path style="stroke:none;" d=""/>
</symbol>
<symbol overflow="visible" id="glyph0-1">
<path style="stroke:none;" d="...."/>
</symbol>
</defs>
```

2. use of symbol defs:
```
<g id="surface1">
<g style="fill:rgb(0%,0%,0%);fill-opacity:1;">
  <use xlink:href="#glyph0-1" x="83.978427" y="98.984416"/>
</g>
<g style="fill:rgb(0%,0%,0%);fill-opacity:1;">
  <use xlink:href="#glyph1-1" x="267.056991" y="98.984416"/>
</g>
<g id="surface1">
```

**Comment by qcts33** [comment]
I can give it a try.
Can you point some reference about the inkscope extension? I don't quite understand what the effect() function is doing.

**Comment by wanglongqi** [comment]
There is very little documents about inkscape extension on web except for those in official wiki. You only need to implement the merge function to get the extension work:

`    def merge_???_svg(self, svg_file):
`

Just follow the codes of the two merge function, you should be able to add in another convertor.

**Comment by wanglongqi** [comment]
@qcts33 it looks like merger for `pdf2svg` is partially working for `pdftocairo`. Please refer to [this commit](https://github.com/wanglongqi/WriteTeX/commit/9eed32047b9b76802d80124409359c42f10fcb6b). 
The convertor does not place the result in the correct place, but it looks like the merger works correctly.
