### ISSUE TITLE
update needed for Inkscape version 1.0

### ISSUE THREAD

**Issue by brynnd** [wanglongqi/WriteTeX#18]
Hello,
Thank you for providing this extension for Inkscape users!

This is just to let you know that most 3rd party Inkscape extensions, like this one, probably will not work with the upcoming new Inkscape version, the long-awaited version 1.0.

Here is the info you need to update this extension, so that it will work with 1.0 and future versions.  
https://wiki.inkscape.org/wiki/index.php?title=Updating_your_Extension_for_1.0

If you have further questions, you can contact Inkscape developers via [mailing lists](https://lists.inkscape.org/postorius/lists/?all-lists), [forum](https://inkscape.org/forums/extensions/), or the [chatroom](https://chat.inkscape.org/channel/inkscape_extensions).

If you have already updated it, please disregard this message.

All best,
brynn

**Comment by alphamodel** [comment]
Thanks for notification, we will modify the code accordingly. Current changes are showing here #20. 

We still need time to think how to solve the incompatibility between different versions. The api changes are quite big.

**Comment by wanglongqi** [comment]
The API changes are quite dramatic, may need to find a better way to handle it. Inkscape 0.9.X and 1.0.X may need to be supported at the same time. Let's try to explore whether possible to make one version to support all of them.

**Comment by wanglongqi** [comment]
The short answer is no. The API changes are very large, we has to split it into two versions.
