### ISSUE TITLE
建议直接使用 mathjax 进行公式渲染

### ISSUE THREAD

**Issue by pluveto** [wanglongqi/WriteTeX#19]
可以大幅度减少依赖

**Comment by alphamodel** [comment]
You are welcomed to submit PR.

**Comment by pluveto** [comment]
> You are welcomed to submit PR.

Made it: https://github.com/pluveto/Mathink

**Comment by alphamodel** [comment]
@pluveto Great work.

**Comment by alphamodel** [comment]
The first step seems to be very promising. I think this one can be a great component in the pipeline. Essentially, it can be used as a latex to svg converter.

May I ask whether the solution is for Windows only or also possible to run on Linux and Mac using something like Mono?

**Comment by pluveto** [comment]
@alphamodel the core lib(MathWpf) is based on .NET Core so it can be easily migrate to other OS. Currently it suit my needs but in fact it supports limited tex syntax. Maybe some day we can impl it as a Chrome App which can be use anywhere with every Mathjax sytax.

**Comment by alphamodel** [comment]
Integrating Mathjax will need a javascript engine, which may also make things complicated.

It would be great if you can make a command line tool to convert latex file to svg file like `pdf2svg`. It will be great if you can also provide binary files for multiple OS. I agree with you that this kind of rending engine may satisfy many users' needs. Then we can try to integrate it into this extension, and everyone get a `lite` version of this extension without the need to install TeX suite. How do you think about it?

**Comment by alphamodel** [comment]
There is a [nodejs application](https://github.com/mathjax/mathjax-node-cli) that can use Mathjax to convert latex to svg. However, it needs user to install nodejs and corresponding dependencies. To me, it doesn't look like the right way to go.
