### ISSUE TITLE
`PDFCROP` does not output the cropped pdf.

### ISSUE THREAD

**Issue by wanglongqi** [wanglongqi/WriteTeX#2]
Under MAC OSX and Linux conditions, the package with `pdfcrop` works well. However, I found the `pdfcrop` command does not produce any output under a standard Windows installation. I failed in finding what is happening here. The `pdfcrop` command was executed, but the cropped pdf does not produced.

I will look into this when I have time. Anyone has any thought on this issue?

**Comment by wanglongqi** [comment]
Progress on this bug:
1. bug coming from executing `pdfcrop`
2. bug is somehow related to path
3. bug is caused by `pdfcrop` calling perl script 
4. replace the input path sep cannot fix the problem
5. escape the input path cannot fix the problem

Conclusion: no method to fix the bug now.

**Comment by carlodri** [comment]
This is what happens to me on Windows 10:

```
Error in pdfcrop:
 CMD executed: pdfcrop "f:\appdata\temp\writetex-2hcokn\writetex.pdf"
PDFCROP 1.38, 2012/11/02 - Copyright (c) 2002-2012 by Heiko Oberdiek.

!!! Error: Copy from `f:\appdata\temp\writetex-2hcokn\writetex.pdf' to `tmp-pdfcrop-8720-img.pdf' failed (No such file or directory/Access is denied)

Process will continue without crop
```

but actually the rendered LaTeX appears correctly inside Inkscape...

**Comment by wanglongqi** [comment]
@carlodri It seems pdfcrop introduces a lot of problems. I am thinking to remove it from the code.

**Comment by wanglongqi** [comment]
@carlodri Can you test the newest version in the repository. I removed `pdfcrop` from the source and added a crop function for `pdf2svg`.

**Comment by wanglongqi** [comment]
Because `pdfcrop` is removed from the project. This issue is closed.

**Comment by carlodri** [comment]
@wanglongqi works great! Thank you and sorry for now answering before!

**Comment by wanglongqi** [comment]
@carlodri You are welcome, thanks for the feedback!
