### ISSUE TITLE
Latex error : writetex.log not found

### ISSUE THREAD

**Issue by rusandris** [wanglongqi/WriteTeX#22]
Hey, I try to use Writetext in Inkscape on Ubuntu. I installed it, Inkscape recognizes the extension, but I get the following error:
`
/bin/sh: 1: pdflatex: not found
Latex error: check your latex file and preamble.
 CMD executed: pdflatex "-output-directory=/tmp/writetex-Nf8gwq" -interaction=nonstopmode -halt-on-error "/tmp/writetex-Nf8gwq/writetex.tex" > "/tmp/writetex-Nf8gwq/writetex.out"
Traceback (most recent call last):
  File "writetex.py", line 360, in <module>
    e.affect()
  File "/home/rusandris/snap/inkscape/5874/extensions/inkex.py", line 289, in affect
    self.effect()
  File "writetex.py", line 166, in effect
    print(open(log_file).read(), file=sys.stderr)
IOError: [Errno 2] No such file or directory: '/tmp/writetex-Nf8gwq/writetex.log'
`
I added pdflatex to my PATH variable, still get this error. Can you anyone help me with 
![issue](https://user-images.githubusercontent.com/62118955/77947144-22be1980-72cc-11ea-84b3-1aac5fdb7c92.png)
this?

**Comment by alphamodel** [comment]
```
/bin/sh: 1: pdflatex: not found 
Latex error: check your latex file and preamble.
....
```

**Comment by rusandris** [comment]
Again, I have pdflatex, added to PATH still getting this error. Should I be doing something else?

**Comment by alphamodel** [comment]
This is a system environment problem. It is very hard to diagnose without access to your system. Based on the error message, Python used by inkscape cannot find `pdflatex`.

You can try to use [custom latex cmd](https://writetex.tk/latexcmd.html) to override the command to be executed.

**Comment by alphamodel** [comment]
@rusandris you may try to use the latest commit, in which an additional path field is introduced. You can check #23 for more details.
