### ISSUE TITLE
Does not work with inkscape

### ISSUE THREAD

**Issue by fu123456** [wanglongqi/WriteTeX#24]
'''text
writetex.py:33: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("-f", "--formula",
writetex.py:37: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("-p", "--preamble",
writetex.py:41: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--read-as-line",
writetex.py:45: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("-s", "--scale",
writetex.py:49: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("-i", "--inputfile",
writetex.py:53: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("-c", "--pdftosvg",
writetex.py:57: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("--action", action="store",
writetex.py:60: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("-r", "--rescale",
writetex.py:64: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("-l", "--latexcmd",
writetex.py:68: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option("-t", "--tosvg",
writetex.py:356: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed.
  e.affect()
writetex.py:290: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
  doc = inkex.etree.parse(svg_file)
writetex.py:281: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
  svgout = inkex.etree.Element(inkex.addNS('g', 'WriteTexNS'))
Traceback (most recent call last):
  File "writetex.py", line 356, in <module>
    e.affect()
  File "/usr/share/inkscape/extensions/inkex/deprecated.py", line 180, in affect
    return self.run(args=args)
  File "/usr/share/inkscape/extensions/inkex/base.py", line 123, in run
    self.save_raw(self.effect())
  File "writetex.py", line 172, in effect
    self.merge_pdf2svg_svg(svg_file)
  File "writetex.py", line 294, in merge_pdf2svg_svg
    WriteTexNS] = self.text.encode('string-escape')
LookupError: unknown encoding: string-escape

'''

**Comment by wanglongqi** [comment]
What is your inkscape version?

**Comment by wanglongqi** [comment]
No enough information provided. Close the issue.
