### ISSUE TITLE
WriteTeX and Inkscape 1.2

### ISSUE THREAD

**Issue by shivaway** [wanglongqi/WriteTeX#28]
The extension does not seem to work with Inkscape 1.2.  Any thoughts on how I can debug / help you debug the situation?

Shawn Way

**Comment by sbelharbi** [comment]
hi,
i am having the same issue.
inkscape: Inkscape 1.2 (1:1.2.1+202207142221+cd75a1ee6d)
this github writetex.

the extension is displayed in the list of extensions.
but when i click, nothing happens.

thanks

**Comment by wanglongqi** [comment]
I can reproduce the error with a non-default Inkscape theme. 

Actually, if you wait enough long, an error dialog will pop out with GTK errors. So my guess would be that non-default themes don't have all icon resources as the default theme. If you roll back to the default theme the extension should work as normal.

<img width="395" alt="image" src="https://user-images.githubusercontent.com/6874783/184614059-6874f861-db32-4951-b6cb-e2744b854f4a.png">

<img width="637" alt="image" src="https://user-images.githubusercontent.com/6874783/184614129-a9c8a8ec-6a02-46c7-9068-ec9717531b30.png">

**Comment by sbelharbi** [comment]
hi,
i rolled back the inkscape theme to the system default one.

![inkscape](https://user-images.githubusercontent.com/23446793/184989777-81aad6ed-42d9-4794-a5e1-e4d4f66e4f6a.png)

i got the same behavior.
clicking on: extensions > writetex, does not do anything. it does not launch the extension.
could it be something related to my installation? python versions? my default system theme (yaru-dark)? is there a preferred theme?

so fare, there is me and @ shivaway who had the issue. (plus you on non default theme.)
this extension is very handy and easy to use. 
now, i am using textext. a bit different, and it yields warning every time it generates text.

thanks

**Comment by coding-javion** [comment]
Hi, I have the same problem.
Inkscape 1.2.1 (9c6d41e410, 2022-07-14)
Windows 10 and Python 3.8.2.

**Comment by shivaway** [comment]
The error that keeps popping up is:

C:\Program Files\Inkscape\bin\pythonw.exe: can't find '__main__' module in 'C:\\Program Files\\Inkscape\\bin'

Hopefully this helps...

**Comment by nathanal** [comment]
This was reported in https://gitlab.com/inkscape/inbox/-/issues/7727, where  OP noted that the error logs reported a missing dependency of inkex. If you open the writetex.inx  and delete the line that says inkex.py, perhaps that will work? https://github.com/wanglongqi/WriteTeX/blob/852484e1618b8e500f4e5211267912cc94d76e98/1.0.x/writetex.inx#L5

**Comment by wanglongqi** [comment]
@nathanal Thanks for your comment! It seems to be a good idea to remove the line as in Inkscape 1.2.1 the inkex module is changed from a file to a folder. I have tested it on Unbuntu 18.04 machine and removing that line will make the extension load again.

@shivaway can you have a try on your machine to test whether the extension will work after removing such a line?
