### ISSUE TITLE
Hello....I follow the instructions and I receive the following error message.

### ISSUE THREAD

**Issue by cesaraceros** [wanglongqi/WriteTeX#4]
Hello:

I follow the instructions to install WriteTeX....and I try to put the equation as Capture01 in inkscape 0.92.2. 

I have installed MikTeX 2.9 (full) that have xelatex and pdf2svg included and the directories are in PATH variable. 

![capture01](https://user-images.githubusercontent.com/12279331/30009123-da5352d0-90f3-11e7-9ae8-79955cc4ebbf.PNG)

When I follow to Apply.....I receive this....Capture02
![capture02](https://user-images.githubusercontent.com/12279331/30009142-fc7c41b4-90f3-11e7-95b7-a127fd8f4865.PNG)

But at the end the pdf was created....as LaTeX notify me. I check in the temp files but the file doesn't exist. 

![capture03](https://user-images.githubusercontent.com/12279331/30009160-0b70737a-90f4-11e7-9d91-113c0ea56548.PNG)

Thank you for your support.

Cesar

**Comment by wanglongqi** [comment]
The input is not a valid TeX string. Try to use $ or $$ to surround the string, e.g. $\alpha$ instead of \alpha.

**Comment by wanglongqi** [comment]
Very strange, the pdf file is not exist while loading it. Try comment out these lines: 

https://github.com/wanglongqi/WriteTeX/blob/b1f9deead9bb031625ede4d66a0f89bb10fb2194/writetex.py#L181-L192 

See if the files are existing after execution.

**Comment by cesaraceros** [comment]
Hello....I made your changes and the directory was created but the PDF doesn't appear. I was working with the WriteTeX 1.1. I decide to move to WriteTeX 1.6.1 with a totally fresh installation of Inkscape 0.92.2 and now is working. Your work is very important I appreciate it a lot. Inkscape must consider seriously include writetex as a default extension. Thank you.

**Comment by wanglongqi** [comment]
Thanks. Equation support is not a mandatory function for Inkscape users, most of the users do not require such a function.
