### ISSUE TITLE
IndexError on use

### ISSUE THREAD

**Issue by ahhsia** [wanglongqi/WriteTeX#6]
Hello, 

I get an *IndexError* when WriteTex runs.
![screenshot from 2017-11-02 16-53-48](https://user-images.githubusercontent.com/2042495/32355090-5e8d9a06-bff2-11e7-8ca0-7f7670831a09.png)

I am running Inkscape 0.92.2

**Comment by wanglongqi** [comment]
Very strange error. Can you provide more detail information? 

Meanwhile, please also test [this version].(https://raw.githubusercontent.com/wanglongqi/WriteTeX/why_xpath_not_working/writetex.py)
